export const DASHBOARD_URL_NEWS_LIST = '/social-events.json'
export const DASHBOARD_REQUEST_NEWS_LIST = 'DASHBOARD_REQUEST_NEWS_LIST'
export const DASHBOARD_REVEIVE_NEWS_LIST = 'DASHBOARD_REVEIVE_NEWS_LIST'

export const DASHBOARD_RECEIVE_SELECTED_NEWS_DETAIL = 'DASHBOARD_RECEIVE_SELECTED_NEWS_DETAIL'
export const DASHBOARD_CLOSE_NEWS_ANALYSIS_DETAIL_POPUP = 'DASHBOARD_CLOSE_NEWS_ANALYSIS_DETAIL_POPUP'